services:
  - type: web
    name: repassify-web
    runtime: node
    plan: free
    buildCommand: npm install && npm run build -w packages/core && npm run build -w apps/web
    startCommand: npm run start -w apps/web
    envVars:
      - key: NEXT_PUBLIC_API_BASE_URL
        value: https://repassify-api.onrender.com

  - type: web
    name: repassify-api
    runtime: node
    plan: free
    buildCommand: npm install && npm run build -w packages/core && npm run build -w packages/db && npm run db:migrate && npm run db:seed:admin && npm run build -w apps/api
    startCommand: npm run start -w apps/api
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_URL_DIRECT
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: REPASSIFY_ADMIN_EMAIL
        value: admin@repassify.com
      - key: REPASSIFY_ADMIN_PASSWORD
        sync: false
      - key: REPASSIFY_ADMIN_NAME
        value: Admin Master
      - key: WEB_ORIGIN
        value: https://repassify-web.onrender.com
      - key: API_PUBLIC_URL
        value: https://repassify-api.onrender.com
      - key: SHOPEE_BASE_URL
        value: https://partner.shopeemobile.com
      - key: SHOPEE_PARTNER_ID
        sync: false
      - key: SHOPEE_PARTNER_KEY
        sync: false
      - key: SHOPEE_REDIRECT_URI
        value: https://repassify-api.onrender.com/v1/channels/shopee/auth/callback
